{
 "title": "mystrom",
 "description": "mystrom",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Power consumption",
   "type": "timeseries",
   "description": "Current power consumption from my strom:",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "mystrom_power{\n}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temparatur",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mystrom_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Power Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg(mystrom_average_power) * $__range) / 3600000) * on(device) group_left() mystrom_power_cost / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Power Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(mystrom_average_power) * $__range) / 3600000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}