apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ../../base/apps/nextcloud
  #- ../../base/apps/wordpress
  - ../../base/apps/kube-promstack
  - ../../base/exporters/mystrom
patches:
  - path: ./patches/nc.yaml
    target:
      kind: Application
      name: nextcloud
  # - path: ./patches/wordpress-1.yaml
  #   target:
  #     kind: Application
  #     name: wordpress-1
  - path: ./patches/prom.yaml
    target:
      kind: Application
      name: kube-prom-stack
  - path: ./patches/mystrom.yaml
    target:
      kind: Pod
      name: mystrom-exporter
