apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  #- ../../base/apps/exporters/
  - ./custom-dashboard.yaml
  - ./secrets
patches:
  - path: ./patches/prom.yaml
    target:
      kind: Application
      name: kube-prom-stack
  - path: ./patches/mystrom.yaml
    target:
      kind: Deployment
      name: mystrom-exporter
  - path: ./patches/pve-nodexporter-patch.yaml
    target:
      kind: ScrapeConfig
      name: proxmox
