apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apps/nextcloud
patches:
  - path: ./patches/nc.yaml
    target:
      kind: Application
      name: nextcloud
