apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-externalinstance.yaml
  - ./dashboards/pve-dashboard.yaml
  - ./dashboards/mystrom-exporter-dashboard.yaml
  - app.yaml
