apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wp-template
spec:
  destination:
    name: ""
    namespace: wp-template
    server: https://kubernetes.default.svc
  sources:
    - path: ""
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 24.1.9
      directory:
        jsonnet:
          tlas:
            - {}
      chart: wordpress
      helm:
        valueFiles:
          - $values/base/apps/wordpress/values.yaml
    - repoURL: "https://github.com/kubierend/bladman.git"
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
