apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: proxmox
  namespace: monit
  labels:
    release: kube-prom-stack
spec:
  staticConfigs:
    - labels:
        job: prometheus
      targets:
        - 192.168.1.10:9100
