---
apiVersion: v1
kind: Pod
metadata:
  name: patch
spec:
  containers:
    - name: exporter-go-mystrom
      env:
        - name: MYSTROM_IP
          value: "192.168.1.237"
      args:
        [
          "--web.listen-address=0.0.0.0:9452",
          "--web.device-path=/device",
          "--target=$(MYSTROM_IP)",
          "--municipality=Bern",
        ]
