---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  destination:
    namespace: observability-system
  source:
    helm:
      valuesObject:
        grafana:
          persistence:
            storageClassName: proxmox-data
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: proxmox-data