---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  selector:
    matchLabels:
      app: prometheus-pve-exporter # Match the app label from the pod
  podMetricsEndpoints:
    - portNumber: 9221 # Port to scrape from the pod
      path: /pve #?target=192.168.1.46 # Default metrics endpoint
      params:
        target: ["192.168.1.10"]
      interval: 3s #
      scheme: http