apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocis
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: ocis
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: oci://ghcr.io/kubierend/ocis
    targetRevision: 0.7.0
    chart: ocis
    helm:
      parameters: []
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - ocis.k8s.arnsi.ch
          tls:
            - secretName: ocis-tls
              hosts:
                - ocis.k8s.arnsi.ch
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
