---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  destination:
    namespace: monit
  source:
    helm:
      valuesObject:
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx-ingress
            annotations:
              kubernetes.io/ingress.class: nginx-ingress
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - grafana.nixk8s.phonkd.net
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.nixk8s.phonkd.net
          # grafana.ini:
          #   server:
          #     domain: kube-prom-stack-grafana-monit-nix-k8s.teleport.phonkd.net
          #     root_url: "https://kube-prom-stack-grafana-monit-nix-k8s.teleport.phonkd.net/"
          persistence:
            storageClassName: nvme-zfs
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx-ingress
            annotations:
              kubernetes.io/ingress.class: nginx-ingress
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - prometheus.nixk8s.phonkd.net
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.nixk8s.phonkd.net
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: nvme-zfs
