---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  destination:
    namespace: monit
  source:
    helm:
      valuesObject:
        grafana:
          ingress:
            enabled: false
          grafana.ini:
            server:
              domain: kube-prom-stack-grafana-monit-nix-k8s.teleport.phonkd.net
              root_url: "https://kube-prom-stack-grafana-monit-nix-k8s.teleport.phonkd.net/"
          persistence:
            storageClassName: nvme-zfs
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: nvme-zfs
