apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: NONE
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.8.2
    chart: kube-prometheus-stack
    helm:
      parameters: []
      valuesObject:
        prometheus:
          deployment: true
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: undefined
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 100Gi
        grafana:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - grafana.k8s.arnsi.ch
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.k8s.arnsi.ch
          persistence:
            enabled: true
            storageClassName: undefined
            size: 1Gi
          grafana.ini:
            server:
              domain: grafana.example.com
              root_url: http://grafana.example.com
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
