apiVersion: v1
data:
  pve.yml: ZGVmYXVsdDoKICB1c2VyOiBwdmVlZXhwb3J0ZXJyQHB2ZQogIHBhc3N3b3JkOiAiYjJ5a0pPaXdrZnp2bDEiCiAgdmVyaWZ5X3NzbDogZmFsc2UK
kind: Secret
metadata:
  creationTimestamp: null
  name: pveyml
  namespace: monit
