apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: NONE
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 27.5.1
    chart: prometheus
    helm:
      parameters:
        - name: server.persistentVolume.size
          value: 80Gi
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
