# k create secret generic --from-literal=PVE_TOKEN= --from-literal=PVE_USER= -o yaml pve-token-secret
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pve-exporter
  namespace: monit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pve-exporter
  template:
    metadata:
      labels:
        app: prometheus-pve-exporter
    spec:
      containers:
        - name: prometheus-pve-exporter
          image: prompve/prometheus-pve-exporter
          ports:
            - containerPort: 9221
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: config-volume
          secret:
            secretName: pveyml
