# k create secret generic --from-literal=PVE_TOKEN= --from-literal=PVE_USER= -o yaml pve-token-secret
apiVersion: v1
kind: ConfigMap
metadata:
  name: pve-config
  namespace: monit
data:
  pve.yml: |
    ---
    pve:
      - url: "https://192.168.1.46:8006"
        api_token_id: "$(PVE_USER)"
        api_token_secret: "$(PVE_TOKEN)"
        verify_ssl: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pve-exporter
  namespace: monit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pve-exporter
  template:
    metadata:
      labels:
        app: prometheus-pve-exporter
    spec:
      containers:
        - name: prometheus-pve-exporter
          image: prompve/prometheus-pve-exporter
          ports:
            - containerPort: 9221
          env:
            - name: PVE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pve-token-secret
                  key: PVE_TOKEN
            - name: PVE_USER
              valueFrom:
                secretKeyRef:
                  name: pve-token-secret
                  key: PVE_USER
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: config-volume
          configMap:
            name: pve-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pve-exporter
  namespace: monit
spec:
  selector:
    app: prometheus-pve-exporter
  ports:
    - protocol: TCP
      port: 9221
      targetPort: 9221
