apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ../../base/apps/nextcloud
  #- ../../base/apps/wordpress
  - ../../base
  - apps/
patches:
  - path: "./patches/prom.yaml"
    target:
      kind: Application
      name: "kube-prom-stack"
  - path: ./patches/mystrom.yaml
    target:
      kind: Deployment
      name: mystrom-exporter
  - path: ./patches/pve-exporter.yaml
    target:
      kind: PodMonitor
      name: pve-exporter-podmonitor

