apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ../../base/apps/nextcloud
  #- ../../base/apps/wordpress
  - ../../base
patches:
  - path: "./patches/prom.yaml"
    target:
      kind: Application
      name: "kube-prom-stack"
  - path: ./patches/mystrom.yaml
    target:
      kind: Pod
      name: mystrom-exporter
